### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by nook24** [brainsum/cookieconsent#3]
I would like to ask you, if you could add any license information to the repository.

**Comment by lucagouty** [comment]
Thank you @pedro-p for the licence 👌  I guess this one can be closed now 

Though I have a question regarding it, does it really has to be `GPLv3` ? 

IMHO it's quite restricting and will limit how widely this project is used by the community.  

I'm all-in for opensource guys, but this mean it cannot be used for most real-life contracts.

TBH I'd really love to use it for one of my customer but I cannot ask them to release all their sources just so I can use this project

**Comment by lgrapenthin** [comment]
I can also sign that this license is a non-starter for almost all of our projects.

While Mr. Stallman and I agree on many topics and I respect him for his works on Emacs, but this license never did anybody any good. Instead of getting more people to make their stuff available open source voluntarily, it gets more people to not use stuff licensed under it.

Not sharing source code is indeed a freedom too, especially in contract negotiations. While I'd always be fine to share source code of reused libs such as this, having to share source code of the whole works source code is not compatible with many commercial contracts in the first place which also protect trade secrets. Especially poor customers who can't afford to by the source code of a whole work won't get the benefits of a library like this, which according to Stallman is "free".

**Comment by pedro-p** [comment]
The license has been updated to ISC.
